# Generated by Django 5.2.15 on 2026-06-18 19:55

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('indice_socioeconomico', models.CharField(blank=True, help_text="Categoría textual, p. ej. 'Medio-Alto'.", max_length=40, verbose_name='índice socioeconómico (categoría)')),
                ('indice_socioeconomico_num', models.FloatField(blank=True, help_text='Valor numérico normalizado (0–1 o 0–100).', null=True, verbose_name='índice socioeconómico (valor)')),
                ('cantidad_habitantes', models.IntegerField(blank=True, null=True, verbose_name='cantidad de habitantes')),
                ('poligono', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='polígono')),
            ],
            options={
                'verbose_name': 'barrio',
                'verbose_name_plural': 'barrios',
                'db_table': 'barrios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('google_place_type', models.CharField(blank=True, help_text='Ej.: restaurant, pharmacy, cafe. Ver tipos de Google Places.', max_length=80, verbose_name='tipo de Google Places')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'rubro',
                'verbose_name_plural': 'rubros',
                'db_table': 'rubros',
                'ordering': ['nombre'],
            },
        ),
    ]
