# Generated by Django 5.2.15 on 2026-06-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_rubros'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='densidad_hab_km2',
            field=models.FloatField(blank=True, null=True, verbose_name='densidad (hab/km²)'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='ind_desempleo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indicador desempleo'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='ind_educacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indicador educación'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='ind_nbi',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indicador NBI'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='ind_ninini',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='indicador NI-NI-NI'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='ips',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = más vulnerable, 5 = mejor nivel socioeconómico.', null=True, verbose_name='Índice de Prioridad Social (1-5)'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='nbi',
            field=models.IntegerField(blank=True, null=True, verbose_name='hogares con NBI'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='seccional',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='barrio',
            name='semaforo',
            field=models.CharField(blank=True, choices=[('ROJO', 'Rojo (bajo)'), ('AMARILLO', 'Amarillo (medio)'), ('VERDE', 'Verde (alto)')], max_length=10),
        ),
        migrations.AddField(
            model_name='barrio',
            name='superficie_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='superficie (ha)'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='total_hogares',
            field=models.IntegerField(blank=True, null=True, verbose_name='total de hogares'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='indice_socioeconomico',
            field=models.CharField(blank=True, help_text='Etiqueta de visualización: Bajo / Medio / Alto.', max_length=40, verbose_name='índice socioeconómico (categoría)'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='indice_socioeconomico_num',
            field=models.FloatField(blank=True, help_text='IPS normalizado a 0-100 (1→0, 5→100).', null=True, verbose_name='índice socioeconómico (0-100)'),
        ),
    ]
