# Generated by Django 5.2.17 on 2026-09-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_barrio_densidad_hab_km2_barrio_ind_desempleo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrio',
            name='indice_socioeconomico_num',
        ),
    ]
