# Generated by Django 5.2.15 on 2026-06-18 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheGooglePlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat_celda', models.FloatField(verbose_name='latitud de celda')),
                ('lng_celda', models.FloatField(verbose_name='longitud de celda')),
                ('cantidad_mismo_rubro', models.IntegerField(default=0, verbose_name='cantidad del mismo rubro')),
                ('cantidad_total_comercios', models.IntegerField(default=0, verbose_name='cantidad total de comercios')),
                ('consultado_at', models.DateTimeField(auto_now_add=True, verbose_name='consultado')),
                ('expira_at', models.DateTimeField(verbose_name='expira')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='catalog.rubro')),
            ],
            options={
                'verbose_name': 'caché de Google Places',
                'verbose_name_plural': 'caché de Google Places',
                'db_table': 'cache_google_places',
                'indexes': [models.Index(fields=['lat_celda', 'lng_celda', 'rubro'], name='cache_googl_lat_cel_e8f252_idx')],
            },
        ),
    ]
