# Generated by Django 5.2.15 on 2026-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachegoogleplaces',
            name='resultados',
            field=models.JSONField(blank=True, default=list, verbose_name='lugares (caché para el mapa)'),
        ),
    ]
