# Generated by Django 5.2.15 on 2026-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_cachegoogleplaces_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachegoogleplaces',
            name='total_resenas',
            field=models.IntegerField(default=0, verbose_name='total de reseñas (proxy de actividad)'),
        ),
    ]
