# Generated by Django 5.2.17 on 2026-09-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_cachegoogleplaces_total_resenas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachegoogleplaces',
            name='total_resenas',
        ),
    ]
