# Generated by Django 5.2.15 on 2026-06-18 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('poblacional', 'Poblacional'), ('actividad_economica', 'Actividad económica'), ('competencia', 'Competencia')], max_length=30)),
                ('score', models.FloatField(verbose_name='score del indicador (0–100)')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'db_table': 'indicadores',
            },
        ),
        migrations.CreateModel(
            name='AnalisisGuardado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_referencia', models.CharField(blank=True, max_length=200, verbose_name='nombre de referencia')),
                ('notas', models.TextField(blank=True)),
                ('favorito', models.BooleanField(default=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('score', models.FloatField(verbose_name='score de viabilidad (0–100)')),
                ('decision', models.CharField(blank=True, choices=[('ALTA', 'Alta viabilidad'), ('MEDIA', 'Viabilidad media'), ('BAJA', 'Baja viabilidad')], max_length=10)),
                ('guardado_at', models.DateTimeField(auto_now_add=True, verbose_name='guardado')),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to='catalog.barrio')),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to='catalog.rubro')),
            ],
            options={
                'verbose_name': 'análisis guardado',
                'verbose_name_plural': 'análisis guardados',
                'db_table': 'analisis_guardados',
                'ordering': ['-guardado_at'],
            },
        ),
    ]
