# Generated by Django 5.2.15 on 2026-06-18 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisguardado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicador',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='analysis.analisisguardado'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.UniqueConstraint(fields=('analisis', 'tipo'), name='unique_indicador_por_tipo'),
        ),
    ]
