# Generated by Django 5.2.15 on 2026-06-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisguardado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección (calle y número)'),
        ),
    ]
