# Generated by Django 5.2.15 on 2026-06-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analisisguardado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisguardado',
            name='competidores',
            field=models.JSONField(blank=True, default=list, verbose_name='competidores directos'),
        ),
    ]
